### ISSUE TITLE
Discuss the idea of using SimpleMDE for Markdown

### ISSUE THREAD

**Issue by MiltonLn** [FlipperPA/wagtailmarkdownblock#3]
I was looking to your implementation of Markdown and i think this is quite simple and awesome but i think the SimpleMDE is more useful than Showdown because of the tools this offers, this doesn't gives a real-time preview but has a button to do it please take a look here: https://simplemde.com/ 
btw, SimpleMDE doesn't suffer problems previewing the tables

You mentioned this:
> However, on the public facing rendering in the template, I actually override the render() method so the JavaScript dependency only exists on the editor side. This also allows front end caching mechanisms like Varnish to benefit without loading another thing on the client side for our users.

But i think i did the same on my SimpleMDE implementation. I recognize my code to achieve SimpleMDE is not simpler that your code to Showdown but we can work on this to made this simpler. Please take a look here: https://github.com/APSL/puput/pull/112

What i really want is that you think about this and discuss with me this idea, i think this will give a better looking markdown editor on wagtail.

If you think is better with Showdown please give me the arguments to be convinced about it

Thank you!

**Comment by FlipperPA** [comment]
That is definitely a cool editor! I'll take a look at your implementation - I think we can make this work. I think there's a trick I've used in the past to override the default editor in Wagtail; we might be able to extend that. I'm hoping to get some cycles later today to take a deeper dive.

**Comment by MiltonLn** [comment]
Ok Tim,
Thanks a lot :)

**Comment by marctc** [comment]
I think that SimpleMDE is a good option. Hard to say if I prefer this instead of showdown if I can't see a demo of both runing in the Wagtail admin editor.

**Comment by MiltonLn** [comment]
@FlipperPA, @marctc.
 Guys!
I'm glad to tell you that i've achieved a very nice implementation of SimpleMDE for this wagtailmarkdownblock and i really need that you support me with this ;)

Answering to @marctc doubts, basically, the @FlipperPA's implementation with showdown is a normal wagtail text field with a preview zone where you can find on real time the markdown results, but, it have a few issues displaying tables per example

This is how Tim's implementation looks, you can see the tables issue there:

<img width="1044" alt="captura de pantalla 2017-07-03 a la s 11 29 32 a m" src="https://user-images.githubusercontent.com/7388681/27801426-977aa792-5fe3-11e7-9154-f5e2640b9b12.png">

Now, my SimpleMDE implementation is a rich editor for markdown that has a lot of features including real time preview on place and with a preview button like GitHub's comments.

This is how my implementation looks, it is worth say that here doesn't exists tables issues:

this is how the editor looks normally.

<img width="900" alt="captura de pantalla 2017-07-03 a la s 11 26 32 a m" src="https://user-images.githubusercontent.com/7388681/27801505-0b19f892-5fe4-11e7-87c4-e5bace38854e.png">

and this is how the editor looks on preview mode.

<img width="823" alt="captura de pantalla 2017-07-03 a la s 11 26 44 a m" src="https://user-images.githubusercontent.com/7388681/27801529-20826a2a-5fe4-11e7-825c-8284e1f42497.png">

Maybe the best part of all is that my implementation respects the Tim's design philosophy for this repository.

I will put a PR with all of this and i'm very looking forward to your opinions about this.

**Comment by MiltonLn** [comment]
Please take a look at:
https://github.com/FlipperPA/wagtailmarkdownblock/pull/5

**Comment by FlipperPA** [comment]
Request merged. Working on Puput merges (many of them) now!

**Comment by at2008** [comment]
I used wagtail2.3 version.
Everything was fine when editing the article in admin area, but after the article was published, the markdown displayed was abnormal. Could you please explain how to use this?
